name: CICD

on: [ push ]

jobs:
  CICD-Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
      - name: Run tests with coverage
        run: |
          make test-coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Run linters
        run: |
          make lint
